# Generated by Django 3.1.1 on 2020-09-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200926_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_ordered',
            new_name='date_order',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
    ]
